### ISSUE TITLE
Unable to download dataset from google drive

### ISSUE THREAD

**Issue by hammadmadu** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#1]
Downloading 1ubvKLzBDe5i1acxgGUK6ObeNBYCKUS07 into /content/drive/MyDrive/Hammad/data.zip... Done.
Unzipping.../usr/local/lib/python3.6/dist-packages/google_drive_downloader/google_drive_downloader.py:78: UserWarning: Ignoring `unzip` since "1ubvKLzBDe5i1acxgGUK6ObeNBYCKUS07" does not look like a valid zip file
  warnings.warn('Ignoring `unzip` since "{}" does not look like a valid zip file'.format(file_id))

I'm trying to download dataset from your provided URL (file_id), but it's showing me above mentioned warnings.

**Comment by abhijitjadhav1998** [comment]
In which module you are getting this error.
`./Model Creation/`
I mean in `preprocessing,model_train or predict`. Please specify it.

And make sure your file uploaded to the drive is a zip file.

**Comment by abhijitjadhav1998** [comment]
Issue is fixed
