### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by jeniffer2q** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#10]
the footer in on the middle of page for [Deepfake_detection_using_deep_learning](https://github.com/abhijitjadhav1998/Deepfake_detection_using_deep_learning) project. also thanks a lot for making this project available.
![git](https://user-images.githubusercontent.com/105545843/168839417-d01b8721-e109-4d07-8662-281754aef41f.jpg)

**Comment by abhijitjadhav1998** [comment]
Will work on that .. you should be able to do it its just small CSS thing 😊

**Comment by jeniffer2q** [comment]
i managed thanks
