### ISSUE TITLE
502 bad geteway running the application via Docker

### ISSUE THREAD

**Issue by masterfugazi** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#12]
I'm getting a '502 bad Gateway' running the application via Docker when I got to http://localhost:80 any suggestions on troubleshooting? -I have both of the images running that were mention in the docks.

**Comment by git-maniesh** [comment]
could you try to config the ngix file and change the gateway timeout time to 600

**Comment by git-maniesh** [comment]
> I'm getting a '502 bad Gateway' running the application via Docker when I got to http://localhost:80 any suggestions on troubleshooting? -I have both of the images running that were mention in the docks.


could you try to config the ngix file and change the gateway timeout time to 600

**Comment by masterfugazi** [comment]
I'll try that today, thanks.

**Comment by masterfugazi** [comment]
Alright so today I was able to get the project to build successfully , I'm not exactly sure what I did, but I re ran the commands from the docs, and it worked!
