### ISSUE TITLE
After video upload '/predict/' gives a Server Error (500).

### ISSUE THREAD

**Issue by masterfugazi** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#13]
Running on Docker, after uploading a video to be scanned upon loading http://localhost/predict/ it gives a Server Error (500). 

Any troubleshooting recommendations would be greatly appreciated! 

Thanks, for replying! I greatly appreciated it.

**Comment by git-maniesh** [comment]
> Running on Docker, after uploading a video to be scanned upon loading http://localhost/predict/ it gives a Server Error (500).
> 
> Any troubleshooting recommendations would be greatly appreciated!
> 
> Thanks, for replying! I greatly appreciated it.

Even I got the same issue but could you please change the internal timeout time in nginx file to 600 or more I gone through many youtube vids and only found this solution

**Comment by masterfugazi** [comment]
Thanks.

**Comment by git-maniesh** [comment]
> Thanks.

Does it worked ?

**Comment by git-maniesh** [comment]
> > Thanks.
> 
> Does it worked ?

Could we connect somewhere insta ,LinkedIn or any platform?

**Comment by masterfugazi** [comment]
I wasn't able to get it to work 100% with Docker, I'm personally not a huge fan of Docker, but do use it here and there so I'm sure it was just my lack of knowledge not being able to get it working with Docker. I ended up getting it to build locally after a few updates locally, thanks for following up!
