### ISSUE TITLE
Enabling working of project on Non Cuda Computers

### ISSUE THREAD

**Issue by Tharun-PS** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#14]
In the readme file, under "We welcome Open Source Contribution", Enabling working of project on Non Cuda Computers. i.e on normal or AMD GPUs is considered not possible as dlib uses CUDA internally. I have modified the code in such a way that the project works very fine on Normal computer's CPU without requiring GPU. Wishing to contribute to the requirements stated in readme file. I'm using Lenovo Ideapad S340 with intel i5 processor.

**Comment by Sushanttech** [comment]
Hi tarun can you send me the project

**Comment by abhijitjadhav1998** [comment]
> In the readme file, under "We welcome Open Source Contribution", Enabling working of project on Non Cuda Computers. i.e on normal or AMD GPUs is considered not possible as dlib uses CUDA internally. I have modified the code in such a way that the project works very fine on Normal computer's CPU without requiring GPU. Wishing to contribute to the requirements stated in readme file. I'm using Lenovo Ideapad S340 with intel i5 processor.

@Tharun-PS  : Please submit a Pull request .. will be happy to merge the changes
