### ISSUE TITLE
Installation issue of Torch for CUDA 12 

### ISSUE THREAD

**Issue by parzivalZzz** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#16]
Need help with installation of Torch :  my CUDA version is 12
Even if I'm Installing other versions like CUDA 11.6 / CUDA 11.7. Its not working in my device.  I tried installing from the website and It says something like : 
"Could not find a version that satisfies the requirement torch==1.12.1 (from versions: )
No matching distribution found for torch==1.12.1 "
Also I've tried installing torch separately, versions like : 1.4.0, 0.1.2, 1.9.0, 1.9.0+cu111
It still shows the same thing that  : No matching  distribution found.
![IMG-20230313-WA0003](https://user-images.githubusercontent.com/93007848/224598473-0e42cf5f-d035-4f1b-949f-abf15e1d9733.jpg)

**Comment by abhijitjadhav1998** [comment]
as already mentioned in readme and video you need to install torch separately
