### ISSUE TITLE
Facing Sequence Error

### ISSUE THREAD

**Issue by anuptilak** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#18]
Hi There, 

I'm new to python and deep learning stuff. I'm facing following error, can someone please guide me to resolve the issue, 

Request Method: | GET
-- | --
http://ec2-13-212-202-36.ap-southeast-1.compute.amazonaws.com:8000/predict/
3.0.5
IndexError
list index out of range
/home/ubuntu/Deepfake_detection_using_deep_learning/Django Application/ml_app/views.py in get_accurate_model, line 196
/usr/bin/python3
3.8.10
['/home/ubuntu/Deepfake_detection_using_deep_learning/Django Application',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/dist-packages',  '/usr/lib/python3/dist-packages']

Internal Server Error: /predict/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Deepfake_detection_using_deep_learning/Django Application/ml_app/views.py", line 268, in predict_page
    model_name = os.path.join(settings.PROJECT_DIR,'models', get_accurate_model(sequence_length))
  File "/home/ubuntu/Deepfake_detection_using_deep_learning/Django Application/ml_app/views.py", line 196, in get_accurate_model
    final_model = sequence_model[0]
IndexError: list index out of range

Thanks
Anup Tilak

**Comment by anuptilak** [comment]
Hi There, 

I could manage to solve the issue, in the code file views.py code tries to get the sequence number by splitting the string and it is splitting the index on the 3rd but when you're deploying the code on the ubuntu server without taking your app out of the repo, the index of string changes. So you need to count your new index and pass it instead of 3 and your code should be up and running. 

Thanks
Anup Tilak

**Comment by pontifex03** [comment]
Can you please tell how to count our new index

**Comment by Vcd2002** [comment]
> Can you please tell how to count our new index

Would you solved this error

**Comment by Vcd2002** [comment]
> Hi There,
> 
> I could manage to solve the issue, in the code file views.py code tries to get the sequence number by splitting the string and it is splitting the index on the 3rd but when you're deploying the code on the ubuntu server without taking your app out of the repo, the index of string changes. So you need to count your new index and pass it instead of 3 and your code should be up and running.
> 
> Thanks Anup Tilak

Sir , please tell me how to pass index value
