### ISSUE TITLE
Please provide training dataset.

### ISSUE THREAD

**Issue by ShalinSuthar** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#2]
Hi, I am working on a similar project and faced an issue to train the model. Can you provide some videos ( the one you demoed in the you-tube video and also in the gif).

**Comment by shivanisbp** [comment]
It has been provided, check this - 
https://github.com/abhijitjadhav1998/Deepfake_detection_using_deep_learning/tree/master/Model%20Creation

**Comment by ShalinSuthar** [comment]
Thanks, got that.

**Comment by JujianRao** [comment]
Hi,the link (https://drive.google.com/file/d/1ubvKLzBDe5i1acxgGUK6ObeNBYCKUS07/view?usp=sharing) you provided in your code of the dataset is invalid.Sorry,I can not find the files through this link,could you please provide a new one?
