### ISSUE TITLE
gobal_metadata.csv not found

### ISSUE THREAD

**Issue by hariprasath112005** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#40]
Error: gobal_metadata.csv file is not found, where can i get that file for training the model

**Comment by luphone04** [comment]
> Error: gobal_metadata.csv file is not found, where can i get that file for training the model

It's [here ](https://github.com/abhijitjadhav1998/Deepfake_detection_using_deep_learning/blob/master/Model%20Creation/labels/Gobal_metadata.csv)

**Comment by hariprasath112005** [comment]
got it

**Comment by luphone04** [comment]
> got it

were you able to run the the model creation code ? and get accuracy specified in the document
