### ISSUE TITLE
error while downloading requirement.txt

### ISSUE THREAD

**Issue by JIBYMARIYAJOSE** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#5]
Iam working in colab. And currently trying to implement the Django part but the  Requirement.txt is not getting downloaded.
<img width="441" alt="error" src="https://user-images.githubusercontent.com/44542906/117675124-ed237980-b1c9-11eb-9091-c1fec2e39108.PNG">
Kindly suggest a solution for it

**Comment by abhijitjadhav1998** [comment]
Hi User
This issue is now resolved. I have updated the command. Actually, the command is pip install -r requirements.txt

Thanks for highlighting the issue.
