### ISSUE TITLE
UNABLE TO INSTALL TORCH IN MY SYSTEM 

### ISSUE THREAD

**Issue by Pavanleela** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#6]
I AM UNABLE TO INSTALL TORCH IN MY SYSTEM PLEASE HELP ME IMMEDIATELY SIR
![C__Windows_System32_cmd exe 25-11-2021 12_34_30](https://user-images.githubusercontent.com/92357036/143395172-1ce53d79-5fad-4d2a-8d6c-006d5ea73607.png)

**Comment by abhijitjadhav1998** [comment]
Hi

Please refer the below video..

https://www.youtube.com/playlist?list=PLNIj0dkfMA1FsD5xR4IEc8vdwr66_WExl

**Comment by Pavanleela** [comment]
can you provide your contact number sir please....its very important

**Comment by abhijitjadhav1998** [comment]
Hey you can ping me on LinkedIn

**Comment by abhijitjadhav1998** [comment]
Please follow this PlayList https://www.youtube.com/playlist?list=PLNIj0dkfMA1FsD5xR4IEc8vdwr66_WExl
