### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by BhargavSpaceO** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#7]
in my macOs giving this error in       model = Model(2).cuda()

**Comment by NarendranM08** [comment]
Can we run it in amd gpu

**Comment by abhijitjadhav1998** [comment]
No currently you can't but it is future Todo list of the project we will be implementing that in future

**Comment by abhijitjadhav1998** [comment]
This is not a issue as dlib only support cuda .
